### ISSUE TITLE
Can't send if senderAddress contains spaces

### ISSUE THREAD

**Issue by sashker** [infobip/oneapi-python#10]
Hello. My registered senderAddress contains space, and if I write it as 'My sender'(example), then JSON formatting wrong:
POST to https://oneapi.infobip.com/1/smsmessaging/outbound/My sender/requests with {'clientCorrelator': 'kwmksrix18', 'senderAddress': 'My sender', 'address': '79227999999', 'message': 'Test message', 'senderName': 'tel:My sender', 'callbackData': 'Any string'}

2015-05-26 07:52:38,047 root         DEBUG    content:<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>

Traceback (most recent call last):
  File "./infobip", line 51, in <module>
    result = sms_client.send_sms(sms, header, data_format)
  File "/usr/lib/python2.6/site-packages/oneapi/__init__.py", line 224, in send_sms
    data_format = data_format
  File "/usr/lib/python2.6/site-packages/oneapi/__init__.py", line 121, in execute_POST
    return is_success, mod_json.loads(response.content)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by maricn** [comment]
Please confirm that version on branch `sender_with_space` (in pull request #11) resolves this issue.

**Comment by sashker** [comment]
I confirm that pull request #11 resolve this issue. Thanks!
